ResourcesAWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Simple AWS SAM App

Resources:
  SodotLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Environment:
        Variables:
          SODOT_API_KEY: !Ref SodotApiKey
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Loader: 
          - .node=file
        Minify: true
        Target: es2020
        EntryPoints:
          - app.ts

